name: tflite_native
version: 0.2.3
author: Dart Team <misc@dartlang.org>
description: A Dart interface to TensorFlow Lite through Dart FFI. This library wraps the experimental tflite C API.
homepage: https://github.com/dart-lang/tflite_native
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  path: ^1.6.2
  quiver: ^2.0.3
dev_dependencies:
  test: ^1.6.4
